from enum import StrEnum


class SessionState(StrEnum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    HEARTBEAT_LATE = "HEARTBEAT_LATE"
    CONTACT_DEGRADED = "CONTACT_DEGRADED"
    USER_WARNING = "USER_WARNING"
    CONTACT_NOTIFICATION = "CONTACT_NOTIFICATION"
    INCIDENT_PENDING = "INCIDENT_PENDING"
    EMERGENCY_ACTIVE = "EMERGENCY_ACTIVE"
    RESPONDER_HANDOFF = "RESPONDER_HANDOFF"
    RESOLVED = "RESOLVED"
    CANCELLED = "CANCELLED"


TERMINAL_STATES = {
    SessionState.RESOLVED,
    SessionState.CANCELLED,
}

